type: baseline

dataset: Hetionet

model:
  name: TransE
  embedding_dim: 50

optimizer:
  class: Adagrad
  lr: 0.02

train:
  loss_function: MarginRankingLoss
  num_epoch: 100
  num_negative: 1
  create_inverse: False

save:
  path: results/baseline/transe_hetionet_ep100

seed: 84