type: baseline

dataset: Hetionet

experiment_name: 'TransE trained optimizing only Compound Treats Disease'
model:
  name: TransE
  embedding_dim: 300

optimizer:
  class: Adagrad
  lr: 0.02

train:
  loss_function: MarginRankingLoss
  num_epoch: 500
  num_negative: 61
  create_inverse: False
  evaluation_relation_whitelist:
    - 'CtD'

save:
  path: results/baseline/transe_hetionet_only_ctd_relation

seed: 84